# CodeCov configuration for lua-resty-yar
# Docs: https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
