# distribution config for opm packaging
name=lua-resty-yar
abstract=High-performance Yar RPC server for OpenResty, built on lua-yar
version=0.1.0
author=fangfengxiang
is_original=yes
license=apache2
lib_dir=lib
doc_dir=lib
repo_link=https://github.com/fangfengxiang/lua-resty-yar
main_module=lib/resty/yar/init.lua
requires = luajit, openresty >= 1.19.3.1
